version: '2'

services:
  app:
    build: .
    volumes:
      - ./:/var/www
  nginx:
    image: nginx:alpine
    volumes:
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - app
    ports:
      - 80:80
  mysql:
    image: mysql:5.7.28
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=homestead
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 3306:3306
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
volumes:
  dbdata:
